# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6f3aa152ef5ba013ebab3c811af86f24bc6938ee62188ad136f1d6c6c40e3fb75ff41e5e695a857f76bc45a418a16ee17de77fbbae2709c99a94194b86b7359

test:
  secret_key_base: 6a65c13797de7fd453225889fd08c868d2b95a4963376a8eb81c9151d8cae4243eaec81f76d12adaa5169f8e3c32b0d877c8f36bef7ee06699ce239ddc2a4d83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
